
drop table if exists articles;

create table articles (
  id                            bigint generated by default as identity not null,
  name                          varchar(30) not null,
  price                         float not null,
  quantity                      integer not null,
  constraint pk_articles primary key (id)
);

insert into articles (name, price, quantity) values('Test01', '1.0', 10);
insert into articles (name, price, quantity) values('Test02', '2.0', 9);
insert into articles (name, price, quantity) values('Test03', '3.0', 8);
insert into articles (name, price, quantity) values('Test04', '4.0', 7);
insert into articles (name, price, quantity) values('Test05', '5.0', 6);

